### ISSUE TITLE
Use Orbot for *.onion addresses only

### ISSUE THREAD

**Issue by k0gen** [guardianproject/orbot-apple#10]
I can't stress enough how happy I am that Orbot is finally on iOS - Excellent job!

Would it be possible to have a toggle in settings that would enable usage of Orbot for `*.onion` addresses only?

**Comment by tladesignz** [comment]
This would mean to do all DNS resolution through Tor and then route all traffic for the internal IP addresses, which Tor makes up for onion addresses, through Orbot's Network Extension, but not the rest.

While this *might* work, my main problem currently is, that Apple's documentation of Network Extensions is in a really sad state. There are a lot of toggles and levers which suggest, if used right, might achieve something like that, but it's unclear how to.

I'll keep this in the back of my head, but won't promise anything today.

**Comment by eycorsican** [comment]
The following config can work exactly for this purpose, as long as your browser doesn't have features such as DNS over HTTPS enabled.

```ini
[General]
loglevel = trace
logoutput = {{leafLogFile}}
dns-server = 1.1.1.1
tun-fd = {{tunFd}}

always-fake-ip = *

[Proxy]
Tor = socks, {{socksHost}}, {{socksPort}}
Direct = direct

[Rule]
DOMAIN-SUFFIX, onion, Tor
FINAL, Direct
```

I'm using a config like this on macOS to access only .onion service through Tor. All other traffic will either go out directly or through other proxy servers.

**Comment by tladesignz** [comment]
Ah, very interesting, @eycorsican, I didn't think of the possibilities `leaf` provides. Thank you very much *again* for hanging out here and providing insights.

**Comment by MattDHill** [comment]
Very much agree with this feature request. Having *all* traffic indiscriminately proxied over Tor is undesirable in many cases. Is there a desire to implement @tladesignz ?

**Comment by tladesignz** [comment]
> Very much agree with this feature request. Having _all_ traffic indiscriminately proxied over Tor is undesirable in many cases. Is there a desire to implement @tladesignz ?

Huuh. Unfortunately, having it *not* do it, is also undesirable in many cases.
My main angst is, that people who aren't programmers but are in need of strong protection will shoot themselves in the foot with such a feature.

E.g. I just recently stumbled over a website which was served over a normal domain *and* an onion domain, but where at one place, the domain was hardcoded, so one piece of the page was served over the open internet.
Which means, in such a scenario, you will give away the fact, that you're visiting a certain site, to a censor, *although* you thought you were safe because you used the onion domain.

I understand we have 2 different user types here:
- People from democratic countries who use Tor for fun and to browse the dark web or connect to their self-hosted onion services.
- People from authoritarian countries, who use Tor to circumvent censorship and avoid monitoring.

It's hard to serve both profiles at once, and when in doubt, I need to decide for the latter group. Yes, even though they might be a tiny minority. But while the first group might be inconvenienced, the second group might end up in jail or receive other oppressive measures.

We will need to think about how to design the UI, so the second group doesn't get themselves in trouble unknowingly.

**Comment by tladesignz** [comment]
@cstiens, @n8fr8:

I think about providing a toggle under `Settings` for this feature. 

Suggested label: `Only route onion services traffic over Tor`
Short description below: `ATTENTION: This will harm your anonymity and security!`

When the toggle is activated, I'd like to show this text in an alert box:

```
ATTENTION: This will harm your anonymity and security!

All traffic will be routed through your normal internet connection."

"Except traffic to onion services (to domains ending in ".onion") which will be routed through Tor.

If these sites aren't configured correctly, you will leak information to your Internet Service Provider and anybody else listening on that traffic!
```

When the toggle is deactivated, I would immediately stop the VPN, to make sure, people don't think they're already safe again.

Can you please comment your thoughts and possibly improve?

Any preferences for button labels?

**Comment by MattDHill** [comment]
I think this is a great solution. I would suggest, however, inverting the label. Instead of `Only route onion services over Tor` maybe something like `Disable service for non-onion traffic`. That way, they know they are *disabling* (rather than *enabling*) something.

And for the description:
```
ATTENTION: This may harm your anonymity and security!

Only traffic to onion services (to domains/sites ending in ".onion") will be routed over Tor.

Traffic to all other sites will be routed through your normal Internet connection.

If these sites aren't configured correctly, you will leak information to your Internet Service Provider and anybody else listening on that traffic!
```

**Comment by cstiens** [comment]
I think we should have a visual indicator in the browsing UI so that people know when they are in this 'onion site only' mode. 

If they have it enabled, it means they would be using Onion Browser like any other browser, correct? For a normal person, would it be equivalent to using Safari? @tladesignz 

Also, we should think about other easy ways to get into this mode. I can imagine something on the home screen (where we display onion sites) that gives the user a shortcut into this mode.

**Comment by tladesignz** [comment]
> I think we should have a visual indicator in the browsing UI so that people know when they are in this 'onion site only' mode.

Yeah, one hour after writing this, I had the same thought. There needs to be visual indication on the main scene, that the Tor VPN is running in this special mode.

I don't want to rework the UI to match your new design for Orbot Android just yet. Would it be possible that you provide something for the current UI?

E.g. currently we have two images to visualize status (off and on): A big onion and a big highlighted onion. Could there be a third onion pic? Additionally I would place a modified status text under it.

> If they have it enabled, it means they would be using Onion Browser like any other browser, correct? For a normal person, would it be equivalent to using Safari? @tladesignz

I guess you're already living in the future? :-) Currently, this is just about Orbot iOS here, **not** Onion Browser, since current Onion Browser v2 doesn't work with Orbot, at all.
But, true, for an Onion Browser v3, which will rely on Orbot, this needs to be considered.

My preferred behaviour for Onion Browser, though, would be, that Onion Browser completely denies working in that mode, since we already discussed, that Onion Browser shouldn't work *without* a running Tor tunnel, and this unsafe mode is not very far from no tunnel at all.

> Also, we should think about other easy ways to get into this mode. I can imagine something on the home screen (where we display onion sites) that gives the user a shortcut into this mode.

No, I wouldn't want this to be controlled in Onion Browser v3 at all, I think. At max an off-switch at the blocking warning when OB detects this mode.

**Comment by tladesignz** [comment]
Ok, I implemented a first solution. UI can be honed later, when @cstiens full UX rework is available with an iOS adaption.

**Comment by k0gen** [comment]
Perfect!
Waiting for the Orbot TestFlight update.

**Comment by hawk544** [comment]
currently, in iOS onion-only mode is not working.
I mean I turn it on and try to open something *.onion on safari, that does not work ""

> safari cant open the page because the server cant be found

but other sites are working, probably outside the tor because public ip is local and speed is normal.

**Comment by tladesignz** [comment]
Can confirm with latest dev build. Not on macOS, though, just on iOS. 🤬

**Comment by hawk544** [comment]
do we have any thoughts on why this might be happening?

**Comment by tladesignz** [comment]
Just cross-checked. On my iPad which is still running iOS 15 it works just fine. On my iPhone with iOS 16 it breaks. Grml.

**Comment by tladesignz** [comment]
There we are. A little more thinking about the problem lead me to the solution. Fix will be contained in the next release, which will arrive soon. (Most probably version 1.4.1.)

**Comment by maxwellsilverh** [comment]
My iPad runs 16. Orbot fails to connect or stay connected. Also turns off my express vpn. Is there a fix or can I get around using it?

**Comment by tladesignz** [comment]
> My iPad runs 16. Orbot fails to connect or stay connected. Also turns off my express vpn. Is there a fix or can I get around using it?

For the future: Please don't pollute foreign issues. Start your own.

To your question: Sorry, it seems, iOS 16.5 introduced a bug which makes it hard to restart Orbot. It seems, the "VPN"-process doesn't get killed properly, although the system thinks it is. Just keep retrying. In my tests, it seemed, after 1 minute that process gets killed and restarts work again. You can also Clear the cache, that seems to help (In Orbot -> Settings -> Clear Tor Cache, at the very end)
See #67 for a longer discussion.
There's going to be an update which makes it easier to clear the cache soon.

You cannot run 2 "VPN"s at once. That's a limitation of iOS. You will need to switch back to Express VPN manually after you're done with your Orbot session. Sorry.

You can switch on an option in Orbot, which makes it easier to switch back to your other VPN:
"Switch back to last used VPN after stop". Second toggle in Orbot -> Settings.
If Express VPN has the option to "connect on demand" and this is switched on, it will automatically restart on the next network request anything in the background does.

If you don't want to use Orbot, well, then don't use it. If you're asking this, because you came here through the Onion Browser update: I'm sorry. Unfortunately, this is the only way forward: Onion Browser cannot use the newer rendering engine (`WKWebView`) without using Orbot. The older engine (`UIWebView`) is deprecated. Apple wants us to move away. Also, this closes a lot of leaks OB before 3 had, esp. with WebRTC and A/V streaming.

Rest assured, we're not happy with the situation either. This is where Apple's design decisions have lead us. :-/
