### ISSUE TITLE
Content Blocker rules cannot be applied to the GitHub domain

### ISSUE THREAD

**Issue by Quant-ux** [guardianproject/orbot-apple#33]
Although the`Block requests by all for documents on all domains.` rule is in place, `github.com` loads just fine in Safari. The `Block requests by all for documents on *github.com` also has no effect.

![4E5A180E-8B8B-496B-A9E1-94C2FD11EF4D](https://user-images.githubusercontent.com/79327106/196781124-199b1cf5-d695-4ea6-96d2-1036f59931b3.jpeg)

**Comment by tladesignz** [comment]
Just tested this on my iPhone 13 Pro running iOS 16.0.3. Works as expected:

Instead of the website, Safari displays this: "Safari cannot open the page. Error: 'The URL was blocked by a content blocker.'"

What OS version are you running on?

Please make sure, that the "Orbot" content blocker is actually really activated in Settings -> Safari -> Extensions.

There's a bug, at least in iOS 15, where we read the state ("enabled" in your screenshot) but it actually doesn't update when the user disables it while the app is running.

Please also try restarting your device, just to be sure. Thanks!

**Comment by Quant-ux** [comment]
Thank you for taking the time to write this! 

I discovered the culprit and all the blame is on me. I had an exception made for `github.com` in Settings -> Safari -> Content Blockers.

This is embarrassing and I am really sorry for the trouble this might have caused you.

Closing as solved.

**Comment by tladesignz** [comment]
LOL no worries. It was easy to check.
