### ISSUE TITLE
not working on mac 

### ISSUE THREAD

**Issue by LogicDancing** [guardianproject/orbot-apple#44]
Can not connect even add custom bridges which is got from email (macOS Monterey ver12.2.1)
And unfortunately no logs when open Log view.

**Comment by LogicDancing** [comment]
update macOS to 12.6.2. Works!

**Comment by tladesignz** [comment]
Thanks for mentioning this. The macOS version definitely is less stable, I noticed this myself. It's unclear to me, though, why. I continue working on it, and hopefully will get it more stable in the future.

**Comment by LogicDancing** [comment]
Thanks for great work. It works well except some sites. So, by the way,  is it possible like orbot-android which provides an HTTP Proxy for connecting web browsers and other HTTP client applications into the Tor SOCKS interface?

**Comment by LogicDancing** [comment]
> Thanks for great work. It works well except some sites. So, by the way, is it possible like orbot-android which provides an HTTP Proxy for connecting web browsers and other HTTP client applications into the Tor SOCKS interface?


Thanks for great work. It works well except some sites. So, by the way, is it possible like orbot-android which provides an HTTP Proxy for connecting web browsers and other HTTP client applications into the Tor SOCKS interface?

**Comment by tladesignz** [comment]
> Thanks for great work. It works well except some sites. So, by the way, is it possible like orbot-android which provides an HTTP Proxy for connecting web browsers and other HTTP client applications into the Tor SOCKS interface?

This information is deliberately randomized and not shown in the UI. Orbot first and foremost is for iOS and a pretty narrow use-case, which is allowed there. It was easy to do a macOS spin, so that's why we did it. There's no intentions to go into competition with Tor Project's own releases for general computer use.

On macOS, if you want to get fancy with Tor, the right choice is to just install it and go crazy on its configuration.

My choice for installing Tor on Mac is [Homebrew](https://brew.sh).
So install Homebrew as described on their page and then install and run Tor:

```sh
brew install tor
./tor
```

Here's a list of all command line and tor.rc options: https://2019.www.torproject.org/docs/tor-manual.html.en

Check out the `SocksPort` configuration option for what you're asking.

Have fun!
