### ISSUE TITLE
Orbot not working under ipados 16.5

### ISSUE THREAD

**Issue by sig0815** [guardianproject/orbot-apple#61]

**Comment by tladesignz** [comment]
Can you get a little more precise? I have it working just fine.

Sometimes it doesn't want to start the first time. Feels like a bug in iOS.

Sometimes, too many cached info about the Tor network accumulates, which creates too much RAM usage when Tor starts up and loads all of it into memory.

Then we get killed by iOS, because VPNs aren't allowed to use more than 50 MByte RAM.

In that case, go to Settings -> Delete Tor Cache (at the very end; stop Tor first!)

**Comment by regevt** [comment]
also does not work for me.
i went as far as reinstalling the app.

i tried the auto mode and also each and every one of the options and still nothing.

what logs do you need and how do i get them.

**Comment by R-a-l-f** [comment]
There is no way to establish an Internet connection, all details I can provide are already provided by
[ Orbot dependency breaks Onion Browser #427 ](https://github.com/OnionBrowser/OnionBrowser/issues/427). I can't comment on other iPadOS releases, since I just installed it today.

**Comment by tladesignz** [comment]
Thank you folks for letting me know. Remedies for this will be tracked here: #67

**Comment by tladesignz** [comment]
https://twitter.com/tladesignz/status/1672202386310307840
