### ISSUE TITLE
[iOS] Content blocker changes don't apply when app unfocused

### ISSUE THREAD

**Issue by Scripter17** [guardianproject/orbot-apple#68]
Device: iPhone XR, iOS 17 dev beta 2
Orbot version: 1.6.1

For some reason, changing a content blocker only applies those changes when the editor is exited (the popup thing beings swiped down). This keeps tripping me up when trying to rapidly iterate blocker settings because I'll switch to safari, notice it doesn't work, then make more changes.

**Comment by tladesignz** [comment]
The whole blocklist has to be written to disk. That could get ugly, when it gets huge.
But since we only have this little editor, let's assume it won't.
I added code which persists the block list when nothing changes anymore for 1 second. Let me know, if that works for you!

Will be contained in the next release!
