### ISSUE TITLE
Orbot stops itself after 60s when connecting

### ISSUE THREAD

**Issue by golfvoyager1** [guardianproject/orbot-apple#77]
iPhone 13 IOS 16.6. Orbot IOS version 1.6.3. Snowflake original is used.

After clearing TOR cache, Orbots can rarely establish a connection because it stops itself 60 seconds after Start button is clicked. When it stops, `[notice] {GENERAL} Interrupt: exiting cleanly.` appears in the log (and I certainly did not touch the Stop button). Usually bootstrap stuck at 50%. But I think if given more time, it can establish a connection because snowflake works. Sometimes retrying many many times works.

Also, I googled. There's a "new 60s timer when instantiating PacketTunnelProvider" in IOS 16 [1]. I guess it may be relevant because the description in the thread matches this behavior.

Please let me know if more info is needed.

[1] https://developer.apple.com/forums/thread/731820

**Comment by tladesignz** [comment]
Uuuuh, nice! Thank you very much for that link!

Unfortunately, a perfect storm gathered around Orbot, it seems:
- Apple messed with Network Extensions in iOS 16.5, not just with this new timer (which I didn't recognize, yet, TBH), but also with general instability. As others in that thread mention, too. I checked with iOS 17 beta 8 - it should get way better again!
- The Tor network increased, hence the list of microdescriptors of Tor nodes got bigger which increased Tor's memory consumption. Apple imposes Network Extensions (aka "VPNs") with a strict 50 MB RAM limit.I had to work with Tor Project, to get that under control again, the result of that you see with version 1.6.3: It's now possible to start with a warm cache again. Prior I had to remove the cache, so starts got very slow.
- I saw messages flying by, that Snowflake currently has issues. There seems to be some attack going on. I don't think, there's a solution, yet.

So unfortunately, there's no good quick fix for you, besides these measures:
- Switch to iOS 17 as soon as its released.
- Try to switch to Obfs4proxy or a better, yet, a direct connection, if possible.
- Wait it out, until the Snowflake situation improves.

:-/

I'll do something about the timer, though. That doesn't buy us much, but the code should definitely handle that situation. Next week!

**Comment by tladesignz** [comment]
I could add some workarounds and improvements thanks to your hint.

A Snowflake connection should be way more easier to achieve again. Version 1.6.4 containing the fixes is underway.

I'll want to give this some more time in TestFlight (public beta) again compared to the recent emergency releases, so please join here, if you don't want to wait:
https://orbot.app/en/download/

Unfortunately, Snowflake is a little more brittle then other methods, due to its design with a pool of voluntary helpers. It is also still under constant development as the network of helpers grows bigger and it is getting heavier usage.

Sorry. Harder enemies make the more difficult approaches necessary. :-/
