### ISSUE TITLE
v1.6.5 Unable to connect

### ISSUE THREAD

**Issue by rrn21833** [guardianproject/orbot-apple#79]
v1.6.5>Use Custom bridges>Connecting 25~50%（fail）

v1.6.4 Can be connected

I think "Always clear cache before start" is redundant.
![86B2E5FB-C356-421E-BEB2-0C6EB449C53B](https://github.com/guardianproject/orbot-apple/assets/37966911/ed97fd16-ae4a-498a-bc20-1ba622339271)

**Comment by tladesignz** [comment]
Thanks for your feedback.

Unfortunately, the Tor network and the censorship circumvention bridges are under heavy attack in the recent months. Your experience can drastically vary from day to day and region to region.

Unfortunately, Apple pushes a limit of 50 MB memory usage on all "VPN"s. Which is really not much, especially not for a system like Tor. The daily fluctuations may drive memory usage above that limit.

In my experience, what actually worked the most stable is actually custom (Obfs4) bridges. Maybe you just need to fetch new ones. Try "Ask Tor" and then switch to custom bridges, even if Tor suggested something else. If we received some custom ones when asking Tor, this should be prefilled/ your old ones overwritten.


Regarding the wish to remove the "Always clear cache before start" setting:

This is actually not redundant, but creates different behaviour:

- In situations, where the "VPN" component (aka. "Network Extension") scratches hard on the 50 MB limit, this will help you restart, because the Tor client won't load all the cached Tor node microdescriptors again which it has gathered during the last run. (Too many of them will actually use too much memory.) So, when you restart, you will have some time until the Tor client gathered too many of them again.

- On the other hand, esp. when you try to connect via Snowflake and Snowflake has a hard time to find proxies, you *do want to keep the cache*, as that helps you *not* getting over that 50 MB threshold on restart, since loading from cache actually uses less RAM (and time!) than generating all the gathered info again.


I know all this cache fumbling is a crutch, but it's the best we can do in the current situation, where we're constrained from so many sides.

If you use Orbot just because of Onion Browser, please be patient: iOS 17 finally supports proxying `WKWebView` traffic, so there's soon going to come a version of Onion Browser which contains an in-app Tor client again for you to choose (as long as you use iOS 17). That one will have security issues again (like leaking your IP address via WebRTC), but it won't be memory constrained and therefore run faster and more stable.

**Comment by tladesignz** [comment]
Addendum:

The work required to make the client use less RAM unfortunately is non-trivial and resources are limited.

We're also pleading with Apple to raise this arbitrary limit, to at least 128 MB. (Our devices nowadays typically have at least 3 *Giga*byte!) But that won't happen before iOS 18.
