### ISSUE TITLE
Should not have been released in its current form

### ISSUE THREAD

**Issue by jasperweiss** [guardianproject/orbot-apple#81]
Glad to see orbit making its way to iOS, but at this stage it shouldn’t be in the App Store.
First and foremost: it leaks traffic. If you manage to get it to connect, which it barely ever does successfully, it will silently disconnect in the background in less than a minute or so and traffic will be routed outside the VPN again.
I can actually lookup my ip address in the new onion browser and, if networking is even working, it shows my own IP address.

Traffic leaks aside, it just doesn’t work very well. Connecting either takes very long or hangs out right. If it does, pages will not load or only once every 10 attempts or so.

**Comment by tladesignz** [comment]
> Glad to see orbit making its way to iOS, but at this stage it shouldn’t be in the App Store.

Are you aware that Orbot is on the app store since February of 2022? There's about 1 mio usages per month, so there must be some people who find this useful. Throwing out such a statement isn't exactly helpful, tbh. Esp. since this software is free to use and nobody forces you to.

But, yeah. We have problems, currently. (And, unfortunately, their not going to get better, soon.) You can read about the background here:

https://github.com/guardianproject/orbot-apple/issues/79
https://github.com/OnionBrowser/OnionBrowser/issues/443

> First and foremost: it leaks traffic. If you manage to get it to connect, which it barely ever does successfully, it will silently disconnect in the background in less than a minute or so and traffic will be routed outside the VPN again. I can actually lookup my ip address in the new onion browser and, if networking is even working, it shows my own IP address.

Yes. Unfortunately, that's a combination of shortcomings, the Apple platform has:

- We're limited by a really low amount of 50 MB of RAM usage, which is **really** little for something like Tor. iOS kills Network Extensions immediately, when they step over that boundary. Tor (and almost all other software), though, doesn't have a good way to limit that RAM usage to a certain limit exactly.
- If you're not choosing to restart automatically on failure, the "Network Extension" infrastructure (aka. "VPN") will *fail open*. And then there might appear this tiny little gap, before Onion Browser realizes, that Orbot went away and stops all traffic.

> Traffic leaks aside, it just doesn’t work very well. Connecting either takes very long or hangs out right. If it does, pages will not load or only once every 10 attempts or so.

Yeah. Sorry. We're cornered here, unfortunately. We try to keep this afloat as best as possible, but there needs to be some major development effort to bring down the RAM usage of the Tor implementation OR Apple to finally lift this stupid RAM limit of 50 MB for devices, which do have 3 - 6 GB of built-in RAM.


I herewith officially invite you to help with this effort. I'd very much like you to participate in a more constructive manner.

**Comment by jasperweiss** [comment]
> If you're not choosing to restart automatically on failure, the "Network Extension" infrastructure (aka. "VPN") will fail open

If I recall correctly, I did not disable "Automatically restart on error" when I observed the traffic leaks so I downloaded the app again to make sure. I did not manage to recreate the problem this time.
In fact, it actually worked pretty well overall.

> Are you aware that Orbot is on the app store since February of 2022? There's about 1 mio usages per month, so there must be some people who find this useful. Throwing out such a statement isn't exactly helpful, tbh. Esp. since this software is free to use and nobody forces you to.

So my initial experience with the app may not have been very representative because as noted above, it did actually work fine just now. When I tried it last time, it would not connect and stay connected at all. No matter how many times I tried. Although I wasn't able to reproduce it this time, I'm fairly confident that traffic was leaking with "Automatically restart on error" enabled. So based on that experience alone I just could not believe why it was released.

Having seen it work properly now, I realise my initial comment wasn't justified.

I do wonder what exactly caused the problem I had initially however. Could it have something to do with the chosen guard node / entry node? IRC, Tor remembers the guard node and uses the same one for extended periods of time. Is that the case with Orbot as well?

**Comment by tladesignz** [comment]
> If I recall correctly, I did not disable "Automatically restart on error" when I observed the traffic leaks so I downloaded the app again to make sure. I did not manage to recreate the problem this time. In fact, it actually worked pretty well overall.

Yeah. It's fluctuating highly. Totally dependent on the current state of the network. Too many nodes -> crashes all the time, because of too much memory consumption.

> Having seen it work properly now, I realise my initial comment wasn't justified.

Thank you.

> I do wonder what exactly caused the problem I had initially however. Could it have something to do with the chosen guard node / entry node? IRC, Tor remembers the guard node and uses the same one for extended periods of time. Is that the case with Orbot as well?

Pretty sure, it's the memory issue.
