### ISSUE TITLE
Orbot fails to connect iPhone 12

### ISSUE THREAD

**Issue by ingfabby** [guardianproject/orbot-apple#87]
This came to our support email, I added the log the user sent. 

Hello, I have a big trouble with connection to the Tor Network from Orbot for a year now. I also try every configurations with Orbot, I also try a stable built with every configurations with same result. I have iPhone 12 with latest iOS. I’m from Slovakia. I also try Orbot connection trough only GSM 5G network and only trough wifi network without eSim = same result - Orbot disconnect. On my personal Mac - everything works trough Tor browser with Socket5. I’m sending a screenshot with log.
![image0](https://github.com/guardianproject/orbot-apple/assets/28932186/53e9f0f6-9323-4896-aa01-b6d2bfd20bf5)

**Comment by tladesignz** [comment]
Yeah, this is well known. I just recently released a new version which is totally stripped down of any features and doesn't hit the 50 MB memory limit of iOS Network Extensions. That one should work for them.

No Obfs4/Snowflake bridge support anymore, though. That ate too much memory just by having it added, due to the necessary Go runtime.

**Comment by tladesignz** [comment]
There are also a lot of FAQs about it: https://orbot.app/en/faqs/
