### ISSUE TITLE
"CHOOSE HOW TO CONNECT" disappeared

### ISSUE THREAD

**Issue by SadDarkAngel** [guardianproject/orbot-apple#90]
After updating the application, the option to select the connection method disappeared. Now version of app is 1.7.0, Build 47

Can’t select how to connect

iPhone SE 2016 iOS 15.8.2

![04866F60-881B-49D7-8AC3-E14509871DDA](https://github.com/guardianproject/orbot-apple/assets/8866829/b8707e8e-9d97-480e-8115-d0ba34ac4874)

**Comment by tladesignz** [comment]
Yes, I'm sorry.
I had to remove Pluggable Transports support, as it was eating too much memory, even when not in use. (Due to the way, Go gets compiled.)

So, I can't currently bring that back until we have an improved version of Tor which eats less RAM so we can stay within the annoyingly low limit of 50 MByte Apple prescribes us.

Anyhow, your screenshot was very helpful. The app needs to reset the old transport settings. Thanks for that! The next version will have a fix for this!
